# Kubernetes PersistentVolumeClaim 配置（EBS）
# 作者: RJ.Wang
# 邮箱: wangrenjun@gmail.com
# 创建时间: 2025-11-14

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eks-info-app-ebs-pvc
  namespace: rj-webdemo
  labels:
    app: eks-info-app
    storage-type: ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 10Gi
